farma/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  devise_for :users
  get 'rubros/index'
  get 'rubros/new'
  get 'rubros/:id/edit', to: 'rubros#edit', as: 'rubros_edit'
  post 'rubros/create'
  patch 'rubros/update'
  delete 'rubros/:id/delete' , to: 'rubros#delete', as: 'rubros_destroy'
#rutas laboratorios
  get 'laboratorios/index'
  get 'laboratorios/new'
  post 'laboratorios/create'
  get 'laboratorios/edit/:id' , to: 'laboratorios#edit', as: 'laboratorios_edit'
  post 'laboratorios/update'
  get 'laboratorios/delete/:id', to: 'laboratorios#delete', as: 'laboratorios_delete'

  # rutas productos
  get 'productos/index'
  get 'productos/new'
  post 'productos/create'
  get 'productos/edit/:id' , to: 'productos#edit', as: 'productos_edit'
  patch 'productos/update'
  delete 'productos/delete/:id', to: 'productos#delete', as: 'productos_borrar'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

farma/app/models/cliente.rb
class Cliente < ApplicationRecord
end

farma/app/models/laboratorio.rb
class Laboratorio < ApplicationRecord
  has_many :producto
end

farma/app/models/producto.rb
class Producto < ApplicationRecord
  belongs_to :laboratorio
  belongs_to :rubro
end

farma/app/models/proveedor.rb
class Proveedor < ApplicationRecord
end

farma/app/models/rubro.rb
class Rubro < ApplicationRecord
  has_many :producto

end

farma/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

farma/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  

end

farma/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

farma/app/controllers/laboratorios_controller.rb
class LaboratoriosController < ApplicationController
  def index
    @lista= Laboratorio.all
  end

  def new
    @laboratorio= Laboratorio.new
  end

  def create
    laboratorio=Laboratorio.new
    laboratorio.lab_desc=params[:laboratorio][:lab_desc]
    laboratorio.active=params[:laboratorio][:active]
    if laboratorio.save
      redirect_to laboratorios_index_path
    end
  end

  def edit
      @laboratorio= Laboratorio.find(params[:id])

  end

  def update
    laboratorio=Laboratorio.find(params[:laboratorio][:id])
    laboratorio.lab_desc=params[:laboratorio][:lab_desc]
    laboratorio.active=params[:laboratorio][:active]
    if laboratorio.save
      redirect_to laboratorios_index_path
    end

  end

  def delete
    laboratorio= Laboratorio.find(params[:id])
    if laboratorio.destroy
      redirect_to laboratorios_index_path
    end

  end
end

farma/app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :authenticate_user!, except: [:delete, :index]

  def index
  #@lista= Producto.all
  #@lista= Producto.where(rubro_id: 2)
  #cond1= " rubro_id = 1"
  #cond2= "laboratorio_id = 1 "
  #cond3= cond1+" and "+cond2
 #cond3= " descripcion like '%ol' "
 #cond3 = "laboratorio_id IN (1,4) "
 cond3 = "laboratorio_id IN (?) ", [1,4]
  @lista= Producto.where(cond3)
  #@lista= Producto.where(laboratorio_id: [1,4])
  end

  def new
    @producto=Producto.new
  end

  def create
      producto=Producto.new
      producto.laboratorio_id=params[:producto][:laboratorio_id]
      producto.rubro_id=params[:producto][:rubro_id]
      producto.descripcion=params[:producto][:descripcion]
      producto.precio=params[:producto][:precio]
      producto.bcode=params[:producto][:bcode]
      producto.activo=params[:producto][:activo]
      if producto.save
        redirect_to productos_index_path
      end

  end

  def edit
    @producto=Producto.find(params[:id])

  end

  def update
    producto=Producto.find(params[:producto][:id])
    producto.laboratorio_id=params[:producto][:laboratorio_id]
    producto.rubro_id=params[:producto][:rubro_id]
    producto.descripcion=params[:producto][:descripcion]
    producto.precio=params[:producto][:precio]
    producto.bcode=params[:producto][:bcode]
    producto.activo=params[:producto][:activo]
    if producto.save
      redirect_to productos_index_path
    end
  end

  def delete
    producto=Producto.find(params[:id])
    if producto.destroy
      redirect_to productos_index_path
    end
  end
end

farma/app/controllers/rubros_controller.rb
class RubrosController < ApplicationController
  def index
    @datos= Rubro.all
  end

  def new
    @dato= Rubro.new
  end

  def create
    dato=Rubro.new
    dato.rubro_desc=params[:dato][:rubro_desc]
    dato.rubro_iva=params[:dato][:rubro_iva]
    if dato.save
      redirect_to rubros_index_path
    end
  end

  def edit
      @dato= Rubro.find(params[:id])

  end

  def update
    dato=Rubro.find(params[:dato][:id])
    dato.rubro_desc=params[:dato][:rubro_desc]
    dato.rubro_iva=params[:dato][:rubro_iva]
    if dato.save
      redirect_to rubros_index_path
    end

  end

  def delete
    dato= Rubro.find(params[:id])
    if dato.destroy
      redirect_to rubros_index_path
    end

  end
end

farma/app/helpers/home_helper.rb
module HomeHelper
end

farma/app/helpers/laboratorios_helper.rb
module LaboratoriosHelper
end

farma/app/helpers/productos_helper.rb
module ProductosHelper
end

farma/app/helpers/rubros_helper.rb
module RubrosHelper
end

farma/app/views/compartido/_header.html.erb
<header>
  <div class="view intro-2">
     <div class="mask rgba-black-strong flex-center">
       <div class="container">
         <div class="white-text text-center wow fadeInUp">
           <h2>Gestion Farmacia</h2>
           <h5>dw3 -1029</h5>
           <br>
         </div>
       </div>
   </div>
 </div>
</header>

farma/app/views/compartido/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav"> -->
    <ul class="navbar-nav">
      <li class="nav-item ">
        <a class="nav-link" href="<%= home_index_path %>">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= laboratorios_index_path %>">Laboratorios</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= rubros_index_path %>">Rubros</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= productos_index_path %>">Productos</a>
      </li>





               <% if user_signed_in? %>
                  <li class="nav-item">
                <span class="nav-link"><%= current_user.email  %></span>   
                    </li>

                    <li class="nav-item">
                      <%= link_to "Salir", destroy_user_session_path, method: :delete, class: 'nav-link' %>
                    </li>
<% else %>
<li class="nav-item">
      <%= link_to "Registrarse", new_user_registration_path, class: 'nav-link'  %>
       </li>
<li class="nav-item">
  <%= link_to "Ingresar", new_user_session_path, class: 'nav-link' %><br />
</li>
<% end %>

    </ul>
  <!-- </div> -->
</nav>

farma/app/views/laboratorios/_form.html.erb
<%= f.label :lab_desc, 'Nombre:', class: 'form-control' %><br>
<%= f.text_field :lab_desc , class: 'form-control' %> <br>

<div class="form-check form-check-inline">
  <%= f.label :active, 'Activo', :value => 1, class: 'form-check-label' %>
  <%= f.radio_button :active,1, :checked =>true, class: 'form-check-input' %>

  <%= f.label :active, 'Inactivo', :value => 0, class: 'form-check-label' %>
  <%= f.radio_button :active,0, class: 'form-check-input'  %> 
</div>
  <br>
<%= f.submit "Enviar", class: ' btn  btn-primary' %> <br>
<%= link_to "Volver a lista", laboratorios_index_path %>

farma/app/views/laboratorios/edit.html.erb
<h1>Editar Laboratorios</h1>
<%= form_for :laboratorio, url: laboratorios_update_path  do |f| %>
<%= f.hidden_field :id %>
<%= render "form", f: f %>
<% end %>

farma/app/views/laboratorios/index.html.erb
<h1>Laboratorios</h1>
<table class="table ">
  <thead>
<tr>
  <th>Laboratorio</th>
  <th>Activo</th>
  <th colspan='2'> <a href="<%= laboratorios_new_path  %>" class="btn btn-outline-success" >nuevo</a> </th>
</tr>

  </thead>
  <tbody>
    <% @lista.each do |t| %>
    <tr>
      <td><%= t.lab_desc %></td>
      <td><% if  t.active=1   %> <span class="badge badge-success">Activo</span>
<% else  %> <span class="badge badge-danger">Inactivo</span>  <% end %>   </td>
      <td><a href="<%= laboratorios_edit_path(t.id)  %>"  class="btn btn-outline-warning" >Editar</a></td>
      <td><a href="<%= laboratorios_delete_path(t.id)  %>"  class="btn btn-outline-danger" >Borrar</a></td>
    </tr>
    <% end %>
  </tbody>
</table>

farma/app/views/laboratorios/new.html.erb
<h1>Nuevo Laboratorio</h1>

<%= form_for :laboratorio, url: laboratorios_create_path  do |f| %>
<%= render "form", f: f %>
<% end %>

farma/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Farma</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "compartido/menu"  %>
<%= render "compartido/header"  %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <%= yield %>
  </body>
</html>