proy01/config/routes.rb
Rails.application.routes.draw do


  root 'main#index'
#rutas de main
  get 'main/index'
  get 'main/saludo'

#rutas archivo
  get 'archivo/index'
  get 'archivo/new'
  post 'archivo/create'
  get 'archivo/edit/:id', to: 'archivo#edit', as: 'archivo_edit'
  post 'archivo/update'
  get 'archivo/borrar/:id', to: 'archivo#destroy', as: 'archivo_destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

proy01/app/controllers/archivo_controller.rb
class ArchivoController < ApplicationController
    skip_before_action :verify_authenticity_token
  def index
    @personas=Persona.all
  end
  def new

  end
  def create
    @nombre=params[:nombre]
    @apellido=params[:apellido]
    @perso=Persona.new
    @perso.nombre=params[:nombre]
    @perso.apellido=params[:apellido]
     if   @perso.save
        redirect_to archivo_index_path
      else
        render "new"
      end
  end
  def edit
    @id=params[:id]
    @persona=Persona.find(@id)
  end
  def update
    @id=params[:id]
    @persona=Persona.find(@id)
    @persona.nombre=params[:nombre]
    @persona.apellido=params[:apellido]
    if   @persona.save
       redirect_to archivo_index_path
     else
       render "edit"
     end
  end
  def destroy
    @id=params[:id]
    @persona=Persona.find(@id)
    if   @persona.destroy
       redirect_to archivo_index_path
     else
       redirect_to archivo_index_path
     end

  end
end

proy01/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
  def saludo
    
  end
end

proy01/app/helpers/archivo_helper.rb
module ArchivoHelper
end

proy01/app/helpers/main_helper.rb
module MainHelper
end

proy01/app/views/archivo/create.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

Nombre: <%= @nombre %>
<br>
Apellido:
    <%= @apellido %> <br>
  <%= link_to 'Formulario',  archivo_index_path %>
  </body>
</html>

proy01/app/views/archivo/edit.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <title>test</title>
  </head>
  <body>
<h1 class="card" >Archivo#index</h1>
    <form class="" action="<%= archivo_update_path %>"  method="post">
    <p>
      <input type="hidden" name="id" value="<%= @persona.id  %> ">
      <input type="text" name="nombre" value="<%= @persona.nombre  %>" placeholder="ingrese su nombre"> <br></p>
      <p>
        <input type="text" name="apellido" value="<%= @persona.apellido  %>" placeholder="ingrese su apellido"></p>

    <button type="submit" name="button" class="btn btn-primary ">Enviar</button>
    </form>
  </body>
</html>

proy01/app/views/archivo/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <title>test</title>
  </head>
  <body>
<h1 class="card" >Archivo#index</h1>
<table>
  <thead>
    <th>Nombre</th>
    <th>Apellido</th>
    <td colspan="2">
      <a class="btn btn-success" href="<%= archivo_new_path %>">Nuevo </a></td>
  </thead>

<tbody>
<% @personas.each do |p| %>
<tr>


  <td><%= p.nombre %></td>
  <td><%= p.apellido %></td>
  <td>  <a class="btn btn-warning" href="<%= archivo_edit_path(p.id) %>">Editar </a></td>
  <td><a class="btn btn-danger" href="<%= archivo_destroy_path(p.id) %>">Borrar </a></td>
  </tr>
<% end %>
</tbody>


</table>
  </body>
</html>

proy01/app/views/archivo/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <title>test</title>
  </head>
  <body>
<h1 class="card" >Archivo#index</h1>
    <form class="" action="<%= archivo_create_path %>"  method="post">
    <p>
      <input type="text" name="nombre" value="" placeholder="ingrese su nombre"> <br></p>
      <p>
        <input type="text" name="apellido" value="" placeholder="ingrese su apellido"></p>

    <button type="submit" name="button" class="btn btn-primary ">Enviar</button>
    </form>
  </body>
</html>

proy01/app/views/archivo/read.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <ul>
      <li><%=link_to 'Inicio',  main_index_path %></li>
      <li><%=link_to 'saludo',  main_saludo_path %></li>
      <li><%=link_to 'Formulario', archivo_index_path %></li>
    </ul>
Nombre: <%= @nombre %>
<br>
Apellido:
    <%= @apellido %> <br>
  <%= link_to 'Formulario',  archivo_index_path %>
  </body>
</html>

proy01/app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>
<h1>Hola mundo</h1>

proy01/app/views/main/saludo.html.erb
<!DOCTYPE html>
<html lang="es" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

    <h1>Main#saludo</h1>
  </body>
</html>